### ISSUE TITLE
Address Filter Tap Performance Issues

### ISSUE THREAD

**Issue by alanjosephwilliams** [opentraildata/OpenTrails-Mobile#113]
#### Description

The responsiveness of the filter buttons on the search-view is problematic, and degrades the app's UX substantially. When serving locally in the browser or on the emulator, there does not appear to be any problem with taking clicks. However, tapping the buttons on devices seems to be a problem across devices.

I asked @anselmbradford if he had thoughts on debugging:

"Try using console.time() and console.endTime() https://developer.mozilla.org/en-US/docs/Web/API/console.time to benchmark the functions associated with clicking the filters—setSearchFilter() and search() in controllers.js. My initial hunch would be that something like "TrailSearch.perform()" is quite slow and is touching a lot of properties in the $scope perhaps. Try to drill down into the methods that setSearchFilter calls and see if any seems to be particularly time consuming."

**Comment by anselmbradford** [comment]
This appears to be due to the large number of loops that run in this function: https://github.com/codeforamerica/trails-mobile/blob/master/www/js/application/services.js#L228

These loops run hundreds of times with each filter that is added. There is about a 50% increase in processing time for each additional filter that is turned on. Also, they run twice on first app launch. 

Working on where they can be optimized...

**Comment by lovehandle** [comment]
Yeah. The search function is terribly inefficient. Ultimately I think it would make sense to move the search functionality to a datastore (like Web SQL).

**Comment by anselmbradford** [comment]
Just pasting this here for future reference. I used for the following code for benchmarking, which may be useful elsewhere: 

``` javascript
var start = window.performance.now();

// code to check

var end = window.performance.now();
var tm = end - start;
console.log(tm);
```
