### ISSUE TITLE
Mark notifications as read within localstorage

### ISSUE THREAD

**Issue by lovehandle** [opentraildata/OpenTrails-Mobile#71]
Currently, we're pulling notification data from an endpoint then persisting that data into localstorage. We need a way for users to mark notifications as read, and have that persisted within localstorage as well.

**Comment by anselmbradford** [comment]
@rclosner Currently as far as I understand it the behavior is messages are downloaded from the server when the app is opened. Messages can be marked as read (closed by clicking the X) locally and they won't show up again during the session, but when the app is re-launched the same messages would appear again. Is this all correct? If so, then if a `hasRead` flag is persisted in localstorage, wouldn't that mean the messages are still downloaded when the app is launched but are hidden if the localstorage flag exists? If this is the behavior sequence it leads me to wonder whether marking the message as read should be sent to the server and handled there, so that the messages aren't downloaded at all the next time the app is launched.

**Comment by lovehandle** [comment]
@anselmbradford exactly. All data is downloaded exactly once (which is the naive approach to stubbing out remotely hosted data), and stored in localstorage after download. Currently, marking the notification as read does nothing but change the attributes of the js object stored in memory so that it is not visible in the same session.

I totally agree that we'll need to be persisting the "read" information, but I don't think that functionality belongs on the server. I think the server should be agnostic of its clients, and it can easily be accomplished on the client side with a simple timestamp (GET all data from the server that was created/updated after the last time I downloaded data).

I've been trying to think through the best approach to intelligently updating the local datastore, and that seems to be the one approach that stands out. Thoughts?
